#!/bin/bash

#SBATCH --job-name=starccm
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --time=01:00:00
#SBATCH --mem=170000
#SBTACH --partition=ngcm

#SBATCH -o output_file.o
#SBATCH -e error_file.e

cd $SLURM_SUBMIT_DIR

module load starccm

NCORE=40

#Run the job from the working directory
starccm+ -batch -np $NCORE -load hull_bare_equilibrium.sim -batch meshandrun.java  >> hull_bare_equilibrium.txt
